# Generated by Django 2.2.4 on 2019-08-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=125, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nome')),
                ('plataforma', models.CharField(choices=[('steam', 'Steam'), ('gog', 'GOG Galaxy'), ('uplay', 'Uplay')], max_length=10, verbose_name='Plataforma de Ativação')),
                ('os', models.CharField(choices=[('xbox', 'Xbox One'), ('ps4', 'Playstation 4'), ('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'MacOS')], max_length=7, verbose_name='Sistemas Operacionais')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Vídeo')),
                ('image', models.FileField(upload_to='images/', verbose_name='Imagens')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
