# Generated by Django 2.2.4 on 2019-08-28 18:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='os',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'MacOS')], max_length=19, verbose_name='Sistemas Operacionais'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='plataforma',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('steam', 'Steam'), ('gog', 'GOG Galaxy'), ('uplay', 'Uplay')], max_length=15, verbose_name='Plataforma de Ativação'),
        ),
    ]
