# Generated by Django 2.2.4 on 2019-08-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190828_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data de Lançamento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(default=False, verbose_name='Promoção'),
        ),
    ]
