# Generated by Django 2.2.4 on 2019-08-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190828_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='propaganda',
            field=models.BooleanField(default=False, verbose_name='Propaganda'),
        ),
    ]
