# Generated by Django 2.2.4 on 2019-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='aberto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Em aberto?'),
        ),
    ]
