# Generated by Django 2.2.4 on 2019-09-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carrinho_aberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='aberto',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Em aberto?'),
        ),
    ]
