# Generated by Django 2.2.4 on 2019-11-21 02:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191120_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagens'),
        ),
    ]
