# Generated by Django 2.2.4 on 2019-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190915_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='carrinho',
        ),
    ]
