# Generated by Django 2.2.4 on 2019-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_perfil_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='end_bairro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_cep',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_complemento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_numero',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='end_rua',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_bairro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_cep',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_cidade',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=120, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='País'),
        ),
    ]
